#ifndef FILTER_IMPL_FILTER_FILTER_H
#define FILTER_IMPL_FILTER_FILTER_H

#include <all.h>

Unit t_AttestationGate_Filter_Impl_Filter_Filter_initialise_(STACK_FRAME_ONLY);

Unit t_AttestationGate_Filter_Impl_Filter_Filter_finalise_(STACK_FRAME_ONLY);

Unit t_AttestationGate_Filter_Impl_Filter_Filter_timeTriggered_(STACK_FRAME_ONLY);

#endif
